--- Stage 2: Running L-CARE RL Training (Fair Comparison) ---
W0702 19:38:18.678000 153182 site-packages/torch/distributed/run.py:793] 
W0702 19:38:18.678000 153182 site-packages/torch/distributed/run.py:793] *****************************************
W0702 19:38:18.678000 153182 site-packages/torch/distributed/run.py:793] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0702 19:38:18.678000 153182 site-packages/torch/distributed/run.py:793] *****************************************
/root/miniconda3/envs/lcare/bin/python: can't open file '/gemini/code/main.py': [Errno 2] No such file or directory
/root/miniconda3/envs/lcare/bin/python: can't open file '/gemini/code/main.py': [Errno 2] No such file or directory
E0702 19:38:18.921000 153182 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 2) local_rank: 0 (pid: 153214) of binary: /root/miniconda3/envs/lcare/bin/python
Traceback (most recent call last):
  File "/root/miniconda3/envs/lcare/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.5.1', 'console_scripts', 'torchrun')())
  File "/root/miniconda3/envs/lcare/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/root/miniconda3/envs/lcare/lib/python3.10/site-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/root/miniconda3/envs/lcare/lib/python3.10/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/root/miniconda3/envs/lcare/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/envs/lcare/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-07-02_19:38:18
  host      : gjob-dev-593729656797126656-taskrole1-0
  rank      : 1 (local_rank: 1)
  exitcode  : 2 (pid: 153215)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-07-02_19:38:18
  host      : gjob-dev-593729656797126656-taskrole1-0
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 153214)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
